### ISSUE TITLE
Catchup Won’t Play

### ISSUE THREAD

**Issue by aussieboozer** [dimkroon/itvhub-for-kodi#1]
Live TV works fine on my Google CCWTV Kodi 19.4 but no catchup programs will play. I also use the add on a Coreelec box where both live and catchup work.

**Comment by dimkroon** [comment]
@aussieboozer 
Thanks for reporting the issue.
Can provide some details please, like what exactly you are doing and when and how it fails (error messages)?
Can you send a log?

**Comment by dimkroon** [comment]
closed due to outstanding request
