### ISSUE TITLE
Virtual channels will not play

### ISSUE THREAD

**Issue by berkhornet** [dimkroon/itvhub-for-kodi#11]
When selecting a virtual live channel, Kodi get stuck in a "busy" loop. Other users have reported that channels play intermittently.

Tested using a clean install of Kodi 20 on a Windows PC (only ITV hub and dependencies installed) and using Estuary skin, I get the "busy" loop every time. In this test I tried the "Midsomer Murders" channel. The debug log is here:
[kodi.log](https://github.com/dimkroon/itvhub-for-kodi/files/10498000/kodi.log)

FYI, the log also contains warning messages "ListItem.setProperty() is deprecated....."

**Comment by dimkroon** [comment]
Thanks @berkhornet. Is fixed in #12.

BTW, deprecation warnings are about things that will be removed in the next kodi version, but should still work OK in the current version.

**Comment by berkhornet** [comment]
Hi

I've tested on Windows PC/Kodi 20 and all working. Many thanks.
