### ISSUE TITLE
Video player not opening

### ISSUE THREAD

**Issue by marson53** [dimkroon/itvhub-for-kodi#2]
Hi, I'm having a problem with the video player not opening when trying the play anything, when I click  play, I can see its playing  because there is a  blue timer on the bottom left that is counting , and on the bottom right is a spinning circle with working , but there is no picture or sound it just seems like the video player is not starting up, tried fresh install of Kodi with just itvhub installed and it's still the has the same problem, using ver 0.4.0 , Kodi 19.4 , Nvidia Shield, Thanks for any help with this would really appreciate it

**Comment by dimkroon** [comment]
Can you check and let me know if and which other addons do play?
Can you send a debug log please?

**Comment by marson53** [comment]
Thanks for your reply, I have many add-ons installed and they all work , YouTube - BBC iplayer -Twitch - Crackle , and many more, like I  described is just has no picture , the problem is the video player is not kicking in to start the video , I don't think a debug log will show anything I don't get an error when itvhub starts to play

**Comment by dimkroon** [comment]
A debug log shows a lot more than just errors. Moreover, errors may be logged without resulting in a notification on screen. Anyway, I don't have a Shield and there is definitely something going wrong, so the debug log is all we can go on for now.

You could, of course, always ask around on forums targeting the Shield, or kodi in general to see if people have encountered similar problems. The tread where the itvhub addon is discussed is [here](https://forum.kodi.tv/showthread.php?tid=369757), maybe you'll find someone there who is also using a Shield.

BTW, are you using a different skin than default Estuary skin? Your description of a blue timer in the bottom left and a spinning circle in right does not sound like anything I've seen before.

**Comment by marson53** [comment]
I'll look at getting a debug log, it's not the skin I'm using xonfluence, because I've installed a fresh clean copy of Kodi 19.4, using default skin and only itvhub installed and it was still the same,  I'll use this for the debug log, Thanks

**Comment by marson53** [comment]
Should I have it set to debug in the itvhub logging settings

**Comment by dimkroon** [comment]
No I was not blaming the skin, just wondered what that timer and circle ws about.

Yep, enable debug in logging settings, that is of vital importance.
After that, restart kodi, so a new log file will be written.
Replicate the problem and quit playing a short while after the problem occurs.
Then download the log and attach it to your comment.
Alternatively, you can use one of the loguploader or logviewer addons to upload the log to kodi's pastebin.
These will give you a url, which you can post here.
Note: there is a limit to the size of log you can upload, so always restart kodi and don't let the video 'play' too long.
Success

**Comment by marson53** [comment]
OK , hope I've done this right here is a link to my Pastebin with the kodi log , was to big a first, but took out 100's of lines of errors repeating that said this  CDVDVideoCodecAndroidMediaCodec:GetOutputPicture dequeueOutputBuffer failed
2022-10-31 01:00:59.037 T:11626   ERROR <general>: CDVDVideoCodecAndroidMediaCodec::GetPicture dequeueInputBuffer failed
2022-10-31 01:00:59.040 T:11528   DEBUG <general>: CheckIdle - Closing session to https://itvpnp.live.ott.irdeto.com (easy=0x52e597f0, multi=0x96a32fb0)
hope this helps  https://pastebin.com/raw/fxQvknJp

**Comment by marson53** [comment]
Just wanted to Thank you , for helping in trying to fix the problem I was having
I'm happy to say that itvhub is now working, 
yesterday there was a update for the Nvidia Shield 9.1.1
and after updating, the add-on now works perfectly

Thanks for the add-on works great now

**Comment by dimkroon** [comment]
Great, glad it works now!
Many thanks for reporting solution.
