### ISSUE TITLE
How to install on a firestick ?

### ISSUE THREAD

**Issue by m1ctk** [dimkroon/itvhub-for-kodi#3]
As downloading isn't supported how do I install this zip on a firestick ?

**Comment by dimkroon** [comment]
I think the most common procedure is to download the zip using a normal computer and transfer the file to the local file system of the device. In Jkodi you select ''install from zip file' and browse to the file on the local file system. Usually there are also verious option to use file on the local network. so if you have NAS or other file system that is accessible from the network, you can place the zip file there. I'm not familiar with the firestick so I can't be more specific. 

This is, however, not an issue of the addon, but a general question on how to install an addon from zip file. You'll be much better off searching the web, or asking a question on a Kodi forum.
