### ISSUE TITLE
0.5.0 not starting on kodi19.4 -  error in pic attached

### ISSUE THREAD

**Issue by 5icario** [dimkroon/itvhub-for-kodi#7]
![2022-11-26_061034](https://user-images.githubusercontent.com/95689246/204075050-16149a3e-b5b2-4a41-9cfa-d6d83c6c757b.jpg)

**Comment by dimkroon** [comment]
Sicario,
That is interesting, thanks for reporting. 
Can tell exactly what you do when you get this error. And can you upload a new debug log and post a ling here?

**Comment by dimkroon** [comment]
closed due to outstanding request.
